[api_gateway]
host = "0.0.0.0"
port = 50001

[connector]
pool_size = 4

[logging]
level = "debug"

[host_config]
host = "127.0.0.1"
ssh_port = 22022
username = "test"
password = "test"
private_key_path = "resources/test_ssh_keys/id_ed25519"

